### ISSUE TITLE
if you fill out only the Chassis Series with random letters or numbers and click Verifica button, nothing happens

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#11]
**ENVIRONMENT:**
PROD
OS: Windows 10
URL: https://autobook.space/
Browser: Chrome

**STEPS TO REPRODUCE:**
1) open URL in browser
2) type in random letters or numbers in the Chassis Series field
3) click Verifica button

**EXPECTED RESULTS:**
1) bring up an error message to fill out also the Plate Number field

**ACTUAL RESULTS:**
1) nothing happens

**Comment by karlaboga** [comment]
this issue has been fixed together with previous bugs.
@OvidiuS-ops please RETEST

**Comment by OvidiuS-ops** [comment]
Retested on PROD
Closing the bug
