### ISSUE TITLE
404 error page when clicking on COOKIES from Register page

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#2]
**ENVIRONMENT:** PROD
	OS: Windows 10
	URL: https://autobook.space/register/
	Browser: Chrome	  
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) click on COOKIES
	  
**EXPECTED RESULTS:**
	Information regarding the cookie policy
	  
**ACTUAL RESULTS:**
	404 error page

**Comment by sebiboga** [comment]
fixing the bug. please RETEST @OvidiuS-ops

**Comment by OvidiuS-ops** [comment]
Retested on PROD
Closing the bug
