### ISSUE TITLE
asks for the phone number instead of the car plates

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#3]
**ENVIRONMENT:** 
        PROD
	OS: Windows 10
	URL: https://autobook.space/register/
	Browser: Chrome	  
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) click on "inregistreaza" button without filling in any information
	  
**EXPECTED RESULTS:**
	ask for the plate number
	  
**ACTUAL RESULTS:**
	asks for the phone number

**Comment by sebiboga** [comment]
fixing the bug. please RETEST @OvidiuS-ops

**Comment by OvidiuS-ops** [comment]
retested on PROD
Closing the bug.
