### ISSUE TITLE
if you enter a phone number it registers your car without a plate number

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#4]
**ENVIRONMENT:** 
        PROD
	OS: Windows 10
	URL: https://autobook.space/register/
	Browser: Chrome	  
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) fill in only your phone number in the phone section
	2) click "inregistreaza"
	  
**EXPECTED RESULTS:**
	ask for the plate number
	  
**ACTUAL RESULTS:**
	a pop-up appears telling you that your car was registered

**Comment by sebiboga** [comment]
Fixed with the previous commit. 
Please RETEST @OvidiuS-ops

**Comment by OvidiuS-ops** [comment]
Retested in PROD.
Closing the bug.
