### ISSUE TITLE
if you enter in the phone section letters&numbers and you leave the plate number empty, it will register your car

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#6]
**ENVIRONMENT:** 
	PROD
	OS: Windows 10
	URL: https://autobook.space/register/
	Browser: Chrome	  
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) in the phone section, enter letters & numbers
	2) click "inregistreaza"
	  
**EXPECTED RESULTS:**
	1. ask for the plate number
	2. don't allow to add letters in the phone number field
	3. error message telling you that the number introduced is invalid
	  
**ACTUAL RESULTS:**
	a pop-up appears telling you that your car was registered

**Comment by karlaboga** [comment]
this is fixed with the previous build. please RETEST @OvidiuS-ops

**Comment by OvidiuS-ops** [comment]
Retested on PROD
Closing the bug
