### ISSUE TITLE
If you click on Verifica button without feeling in any data in the 2 fields: Plate Number and Chassis Series nothing happens 

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#7]
**ENVIRONMENT:** 
	PROD
	OS: Windows 10
	URL: https://autobook.space/
	Browser: Chrome
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) click on "Verifica" button without feeling in any data in the 2 fields: Plate Number and Chassis Series
		  
**EXPECTED RESULTS:**
	1) error message telling you that you need to fill out the 2 fields: Plate Number and Chassis Series
	  
**ACTUAL RESULTS:**
	nothing happens

**Comment by karlaboga** [comment]
feeling comes from to feel
you fill... so please use this wording instead @OvidiuS-ops

**Comment by karlaboga** [comment]
please RETEST @OvidiuS-ops

**Comment by OvidiuS-ops** [comment]
Retested on PROD
Closing the bug
