### ISSUE TITLE
if you fill out only the plate number and click Verifica button, nothing happens

### ISSUE THREAD

**Issue by OvidiuS-ops** [sebiboga/autobook#9]
**ENVIRONMENT:** 
	PROD
	OS: Windows 10
	URL: https://autobook.space/
	Browser: Chrome
	  
**STEPS TO REPRODUCE:**
	1) open URL in browser
	2) type in a correct plate number in the **Plate Number field**
        3) click **Verifica** button
		  
**EXPECTED RESULTS:**
	1) bring up an error message to fill out also the **Chassis Series** field
	  
**ACTUAL RESULTS:**
	1) nothing happens

**Comment by karlaboga** [comment]
@OvidiuS-ops  this was fixed together with previous bug. 
Please RETEST

**Comment by OvidiuS-ops** [comment]
Retested on PROD
Closing the bug
